/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ISimpleLineIconsAnchor: typeof import('~icons/simple-line-icons/anchor')['default']
    ISimpleLineIconsArrowLeftCircle: typeof import('~icons/simple-line-icons/arrow-left-circle')['default']
    ISimpleLineIconsLogout: typeof import('~icons/simple-line-icons/logout')['default']
  }
}
